### ISSUE TITLE
Pass Parameters to Map Controller/View?

### ISSUE THREAD

**Issue by djrpascu** [djrpascu/EVChargeStations#1]
@jwasilgeo and @andygup hi guys, thanks again for all your help so far! I'm fairly new to Angular, Ionic, and the ESRI JSAPI. What's the right way to pass parameters to my map from different controllers? I have a controller/view with a button to get my geolocation via cordova plugin. I take the lat long from those results and pass it into the map controller and the map changes to my location. I have another controller (browse) which lists each feature in my feature layer REST service. Get the lat/long from that and try to pass into the map, but it only works sometimes (testing in Google Chrome and iOS). I'm using $stateParams to pass the parms. See code in www of this repo. I tried a few different things including using the registry pattern, but I think I'm missing something again. All examples I've seen are using 1 view with 1 controller. Any suggestions? Thanks so much!

**Comment by djrpascu** [comment]
Created a mapService factory with sets/gets for map bindings.

**Comment by jwasilgeo** [comment]
Hey @djrpascu I had no time to respond lately, but glad to hear you've got the factory figured out!

**Comment by djrpascu** [comment]
hey @jwasilgeo ! No worries! Thanks for the follow-up! Still got a long ways to go, but happy with the progress so far. albeit simple stuff!

**Comment by jwasilgeo** [comment]
That's awesome, don't stop!  Just from the title of your project alone it sounds pretty cool.  EV for the win.
