### ISSUE TITLE
Feature Layer Object in Registry Pattern?

### ISSUE THREAD

**Issue by djrpascu** [djrpascu/EVChargeStations#2]
How can I access the Feature Layer object via the registry pattern once loaded? I'm testing out the Closest Facility Task service and would like to get the feature set from the currently loaded feature layer.

Can I get it through the map object? I tried searching the properties and methods, but couldn't find anything.

@jwasilgeo, any ideas? Thanks!

**Comment by jwasilgeo** [comment]
The angular-esri-map registry pattern is only for map instances, but if you try the "custom factory" route you can put whatever you want in there to share among controllers.  https://arcgis.github.io/angular-esri-map-site-v1/#/patterns/create-your-own-factories

But, you can get reference to a layer from the map object if you assigned an `id` property to your `FeatureLayer` when creating it. https://developers.arcgis.com/javascript/3/jsapi/map-amd.html#getlayer

**Comment by djrpascu** [comment]
Sweet! I was using this before you told me about the id property:
map.getLayer(map.graphicsLayerIds[0]).graphics

Which turned out to be referencing the same object! I've updated the feature layer to have an ID, much cleaner.

Thanks!

@pybigos - Got my answer! Thanks! Also figured out how to proxy the Route service through my ArcGIS Online account to bypass login requirements. Thanks!
