### ISSUE TITLE
Getting Error Sometimes Using Closest Facility Service

### ISSUE THREAD

**Issue by djrpascu** [djrpascu/EVChargeStations#3]
More often than not, the I am successfully able to use the closest facility service and find the nearest charge station from my current location. Sometimes I get the following error:

"Input field [Station_ID] was not mapped to a field in the network analysis class "Facilities".  Input field [Property_Business_Name] was not mapped to a field in the network analysis class "Facilities".  Input field [Street_Address] was not mapped to a field in the network analysis class "Facilities".  Input field [City] was not mapped to a field in the network analysis class "Facilities".  Input field [Zip_Code] was not mapped to a field in the network analysis class "Facilities".  Input field [Island] was not mapped to a field in the network analysis class "Facilities".  Input field [Charge_Fees] was not mapped to a field in the network analysis class "Facilities".  Input field [Charger_Location] was not mapped to a field in the network analysis class "Facilities".  Input field [Hours_of_Operation] was not mapped to a field in the network analysis class "Facilities".  Input field [Number_of_Chargers] was not mapped to a field in the network analysis class "Facilities".  Input field [Number_of_Ports] was not"

I'm testing on the browser and able to consistently produce the error while emulating my GPS location with - Lat = 21.359 and Long = -157.922.

Tried searching Google for an answer but couldn't find anything that explains it or fixes it.

@jwasilgeo and @pybigos - Sorry for the constant bother, but thanks so much for both your help so far! :+1:

**Comment by djrpascu** [comment]
Increasing the defaultCutoff value to 100.0 (impedenceAttribute = "Miles") seems to have helped. Shoudln't the error message tell me explicitly if no features are in range? Or am I seeing some generic message?

**Comment by jwasilgeo** [comment]
@djrpascu you might also have more luck with these kinds of situations over on geonet

https://geonet.esri.com/welcome

**Comment by djrpascu** [comment]
@jwasilgeo thanks!
